_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: 0
    expanded: false
    enabled: false
  user__page:
    menu_name: main
    parent: 'menu_link_content:b3b2d33f-e0bf-4f06-bd4d-6aea69f9f4a0'
    weight: -50
    expanded: false
    enabled: true
  user__logout:
    menu_name: main
    parent: 'menu_link_content:b3b2d33f-e0bf-4f06-bd4d-6aea69f9f4a0'
    weight: -49
    expanded: false
    enabled: true
