_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 78a0c3ce-059e-4a9c-bf9f-6c2b6bbf2a75
name: 'Florida DrupalCamp'
mail: info@fldrupalcamp.org
slogan: ' Florida DrupalCamp will be held February 21-23rd, 2025 at Florida Technical College in Orlando, FL'
page:
  403: ''
  404: ''
  front: /node/25
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
